{{- if .Values.bgp.enabled }}
apiVersion: cilium.io/v2alpha1
kind: CiliumBGPAdvertisement
metadata:
  name: service-loadbalancers
  labels:
    advertise: bgp
spec:
  advertisements:
    - advertisementType: Service
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchExpressions:
          - key: fakeSelector
            operator: NotIn
            values:
              - will-match-and-announce-all-services
{{- end }}
