apiVersion: v1
kind: Service
metadata:
  name: kured-metrics
  namespace: kube-system
  labels:
    prometheus.jort.haus/scrape: "true"
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 8080
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: kured
    app.kubernetes.io/name: kured
---
apiVersion: v1
kind: Service
metadata:
  name: secrets-store-csi-driver-metrics
  namespace: kube-system
  labels:
    prometheus.jort.haus/scrape: "true"
spec:
  clusterIP: None
  ports:
    - name: metrics
      port: 8095
      targetPort: metrics
  selector:
    app.kubernetes.io/instance: secrets-store-csi-driver
    app.kubernetes.io/name: secrets-store-csi-driver
