apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-backup-openbao
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  parameters:
    roleName: postgres-backup
    vaultAuthMountPath: kubernetes
    audience: vault
    vaultAddress: https://openbao.service.jort.haus:8200
    objects: |
      - objectName: "aws_access_key_id"
        secretPath: "backup/data/postgres"
        secretKey: "aws_access_key_id"
      - objectName: "aws_secret_access_key"
        secretPath: "backup/data/postgres"
        secretKey: "aws_secret_access_key"
      - objectName: "aws_endpoint"
        secretPath: "backup/data/postgres"
        secretKey: "aws_endpoint"
      - objectName: "aws_region"
        secretPath: "backup/data/postgres"
        secretKey: "aws_region"
      - objectName: "walg_s3_prefix"
        secretPath: "backup/data/postgres"
        secretKey: "walg_s3_prefix"
      - objectName: "username"
        secretPath: "postgres/static-creds/postgres-backup"
        secretKey: "username"
      - objectName: "password"
        secretPath: "postgres/static-creds/postgres-backup"
        secretKey: "password"
