apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: seaweedfs-csi-openbao
  namespace: kube-system
spec:
  provider: vault
  secretObjects:
    - secretName: seaweedfs-csi-config
      type: Opaque
      data:
        - objectName: tls.crt
          key: tls.crt
        - objectName: tls.key
          key: tls.key
        - objectName: ca.crt
          key: ca.crt
        - objectName: security.toml
          key: security.toml
  parameters:
    roleName: seaweedfs-csi
    vaultAuthMountPath: kubernetes
    audience: vault
    vaultAddress: https://openbao.service.jort.haus:8200
    objects: |
      - objectName: "tls.crt"
        secretPath: "seaweedfs-pki/issue/seaweedfs-node"
        secretKey: "certificate"
        secretArgs:
          common_name: "seaweedfs-csi.node.jort.haus"
          ttl: "720h"
        method: "PUT"
      - objectName: "tls.key"
        secretPath: "seaweedfs-pki/issue/seaweedfs-node"
        secretKey: "private_key"
        secretArgs:
          common_name: "seaweedfs-csi.node.jort.haus"
          ttl: "720h"
        method: "PUT"
      - objectName: "ca.crt"
        secretPath: "seaweedfs-pki/cert/ca"
        secretKey: "certificate"
      - objectName: "security.toml"
        secretPath: "seaweedfs/data/csi"
        secretKey: "security_toml"
