apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: cert-manager-cloudflare
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  secretObjects:
    - secretName: cloudflare-api-token
      type: Opaque
      data:
        - objectName: api_token
          key: api-token
  parameters:
    roleName: cert-manager-cloudflare
    vaultAuthMountPath: kubernetes
    audience: vault
    vaultAddress: https://openbao.service.jort.haus:8200
    objects: |
      - objectName: "api_token"
        secretPath: "cloudflare/data/api-token"
        secretKey: "api_token"
