apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: minecraft-backup-openbao
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  secretObjects:
    - secretName: minecraft-backup-restic
      type: Opaque
      data:
        - objectName: restic_repository
          key: RESTIC_REPOSITORY
        - objectName: restic_password
          key: RESTIC_PASSWORD
        - objectName: aws_access_key_id
          key: AWS_ACCESS_KEY_ID
        - objectName: aws_secret_access_key
          key: AWS_SECRET_ACCESS_KEY
        - objectName: aws_region
          key: AWS_REGION
        - objectName: aws_region
          key: AWS_DEFAULT_REGION
  parameters:
    roleName: minecraft-backup
    vaultAuthMountPath: kubernetes
    audience: vault
    vaultAddress: https://openbao.service.jort.haus:8200
    objects: |
      - objectName: "restic_repository"
        secretPath: "backup/data/minecraft"
        secretKey: "restic_repository"
      - objectName: "restic_password"
        secretPath: "backup/data/minecraft"
        secretKey: "restic_password"
      - objectName: "aws_access_key_id"
        secretPath: "backup/data/minecraft"
        secretKey: "aws_access_key_id"
      - objectName: "aws_secret_access_key"
        secretPath: "backup/data/minecraft"
        secretKey: "aws_secret_access_key"
      - objectName: "aws_region"
        secretPath: "backup/data/minecraft"
        secretKey: "aws_region"
