apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: hister-openbao
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  secretObjects:
    - secretName: hister-database
      type: Opaque
      data:
        - objectName: database_username
          key: username
        - objectName: database_password
          key: password
    - secretName: hister-oidc
      type: Opaque
      data:
        - objectName: oidc_client_id
          key: client_id
        - objectName: oidc_client_secret
          key: client_secret
        - objectName: oidc_discovery_url
          key: discovery_url
  parameters:
    roleName: hister
    vaultAuthMountPath: kubernetes
    audience: vault
    vaultAddress: https://openbao.service.jort.haus:8200
    objects: |
      - objectName: "database_username"
        secretPath: "postgres/static-creds/hister-static"
        secretKey: "username"
      - objectName: "database_password"
        secretPath: "postgres/static-creds/hister-static"
        secretKey: "password"
      - objectName: "oidc_client_id"
        secretPath: "authentik/data/hister-oidc"
        secretKey: "client_id"
      - objectName: "oidc_client_secret"
        secretPath: "authentik/data/hister-oidc"
        secretKey: "client_secret"
      - objectName: "oidc_discovery_url"
        secretPath: "authentik/data/hister-oidc"
        secretKey: "discovery_url"
