apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: forgejo
  namespace: {{ .Release.Namespace }}
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`git.jort.haus`)
      kind: Rule
      services:
        - name: forgejo-http
          port: 3000
  tls: {}
