apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: forgejo-openbao
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  secretObjects:
    - secretName: forgejo-database
      type: Opaque
      data:
        - objectName: database_username
          key: username
        - objectName: database_password
          key: password
    - secretName: forgejo-oidc
      type: Opaque
      data:
        - objectName: oidc_client_id
          key: key
        - objectName: oidc_client_secret
          key: secret
    - secretName: forgejo-bootstrap
      type: Opaque
      data:
        - objectName: bootstrap_username
          key: username
        - objectName: bootstrap_password
          key: password
    - secretName: forgejo-config
      type: Opaque
      data:
        - objectName: internal_token
          key: internal_token
        - objectName: lfs_jwt_secret
          key: lfs_jwt_secret
        - objectName: secret_key
          key: secret_key
  parameters:
    roleName: forgejo
    vaultAuthMountPath: kubernetes
    audience: vault
    vaultAddress: https://openbao.service.jort.haus:8200
    objects: |
      - objectName: "database_username"
        secretPath: "postgres/static-creds/forgejo-static"
        secretKey: "username"
      - objectName: "database_password"
        secretPath: "postgres/static-creds/forgejo-static"
        secretKey: "password"
      - objectName: "oidc_client_id"
        secretPath: "authentik/data/forgejo-oidc"
        secretKey: "client_id"
      - objectName: "oidc_client_secret"
        secretPath: "authentik/data/forgejo-oidc"
        secretKey: "client_secret"
      - objectName: "bootstrap_username"
        secretPath: "forgejo/data/bootstrap"
        secretKey: "username"
      - objectName: "bootstrap_password"
        secretPath: "forgejo/data/bootstrap"
        secretKey: "password"
      - objectName: "internal_token"
        secretPath: "forgejo/data/config"
        secretKey: "internal_token"
      - objectName: "lfs_jwt_secret"
        secretPath: "forgejo/data/config"
        secretKey: "lfs_jwt_secret"
      - objectName: "secret_key"
        secretPath: "forgejo/data/config"
        secretKey: "secret_key"
