helmfiles:
  - path: cilium-system/helmfile.yaml
  - path: openbao-csi/helmfile.yaml
  - path: multus/helmfile.yaml
  - path: whereabouts/helmfile.yaml
  - path: ssdp-relay/helmfile.yaml
  - path: seaweedfs-csi/helmfile.yaml
  - path: kured/helmfile.yaml
  - path: traefik/helmfile.yaml
  - path: cert-manager/helmfile.yaml
  - path: authentik/helmfile.yaml
  - path: postgres-backup/helmfile.yaml
  - path: minecraft/helmfile.yaml
