helmfiles:
  - path: cilium-system/helmfile.yaml
  - path: openbao-csi/helmfile.yaml
  - path: seaweedfs-csi/helmfile.yaml
  - path: kured/helmfile.yaml
  - path: traefik/helmfile.yaml
  - path: minecraft/helmfile.yaml
