apiVersion: v1
kind: Secret
metadata:
  name: openbao-kubernetes-auth-reviewer-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: openbao-kubernetes-auth-reviewer
type: kubernetes.io/service-account-token
