apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: authentik-openbao
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  parameters:
    roleName: authentik
    vaultAuthMountPath: kubernetes
    audience: vault
    vaultAddress: https://openbao.service.jort.haus:8200
    objects: |
      - objectName: "secret_key"
        secretPath: "authentik/data/config"
        secretKey: "secret_key"
      - objectName: "postgres_username"
        secretPath: "postgres/static-creds/authentik-static"
        secretKey: "username"
      - objectName: "postgres_password"
        secretPath: "postgres/static-creds/authentik-static"
        secretKey: "password"
      - objectName: "postgres_host"
        secretPath: "authentik/data/config"
        secretKey: "postgres_host"
      - objectName: "postgres_name"
        secretPath: "authentik/data/config"
        secretKey: "postgres_name"
      - objectName: "postgres_port"
        secretPath: "authentik/data/config"
        secretKey: "postgres_port"
      - objectName: "postgres_sslmode"
        secretPath: "authentik/data/config"
        secretKey: "postgres_sslmode"
      - objectName: "postgres_sslrootcert"
        secretPath: "authentik/data/config"
        secretKey: "postgres_sslrootcert"
