apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: authentik-openbao
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  secretObjects:
    - secretName: authentik-config
      type: Opaque
      data:
        - objectName: secret_key
          key: AUTHENTIK_SECRET_KEY
        - objectName: bootstrap_password
          key: AUTHENTIK_BOOTSTRAP_PASSWORD
        - objectName: bootstrap_token
          key: AUTHENTIK_BOOTSTRAP_TOKEN
        - objectName: postgres_username
          key: AUTHENTIK_POSTGRESQL__USER
        - objectName: postgres_password
          key: AUTHENTIK_POSTGRESQL__PASSWORD
        - objectName: postgres_host
          key: AUTHENTIK_POSTGRESQL__HOST
        - objectName: postgres_name
          key: AUTHENTIK_POSTGRESQL__NAME
        - objectName: postgres_port
          key: AUTHENTIK_POSTGRESQL__PORT
        - objectName: postgres_sslmode
          key: AUTHENTIK_POSTGRESQL__SSLMODE
        - objectName: postgres_sslrootcert
          key: AUTHENTIK_POSTGRESQL__SSLROOTCERT
  parameters:
    roleName: authentik
    vaultAuthMountPath: kubernetes
    audience: vault
    vaultAddress: https://openbao.service.jort.haus:8200
    objects: |
      - objectName: "secret_key"
        secretPath: "authentik/data/config"
        secretKey: "secret_key"
      - objectName: "bootstrap_password"
        secretPath: "authentik/data/config"
        secretKey: "bootstrap_password"
      - objectName: "bootstrap_token"
        secretPath: "authentik/data/config"
        secretKey: "bootstrap_token"
      - objectName: "postgres_username"
        secretPath: "postgres/creds/authentik"
        secretKey: "username"
      - objectName: "postgres_password"
        secretPath: "postgres/creds/authentik"
        secretKey: "password"
      - objectName: "postgres_host"
        secretPath: "authentik/data/config"
        secretKey: "postgres_host"
      - objectName: "postgres_name"
        secretPath: "authentik/data/config"
        secretKey: "postgres_name"
      - objectName: "postgres_port"
        secretPath: "authentik/data/config"
        secretKey: "postgres_port"
      - objectName: "postgres_sslmode"
        secretPath: "authentik/data/config"
        secretKey: "postgres_sslmode"
      - objectName: "postgres_sslrootcert"
        secretPath: "authentik/data/config"
        secretKey: "postgres_sslrootcert"
