apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: thanos-objstore
  namespace: {{ .Release.Namespace }}
spec:
  provider: vault
  secretObjects:
    - secretName: thanos-objstore-credentials
      type: Opaque
      data:
        - objectName: access_key_id
          key: access_key_id
        - objectName: secret_access_key
          key: secret_access_key
  parameters:
    roleName: thanos-objstore
    vaultAuthMountPath: kubernetes
    audience: vault
    vaultAddress: https://openbao.service.jort.haus:8200
    objects: |
      - objectName: "access_key_id"
        secretPath: "seaweedfs/data/s3/bindings/thanos"
        secretKey: "access_key_id"
      - objectName: "secret_access_key"
        secretPath: "seaweedfs/data/s3/bindings/thanos"
        secretKey: "secret_access_key"
